#!/bin/bash
### BEGIN INIT INFO
# Provides: phpMonitor
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Monitoring tool for monitoring external systems written in PHP
# Description: Written by Ben Jefferson be.jefferson@brighter-connections.com
### END INIT INFO

start() {
	/opt/phpMonitor/phpMonitor.php /etc/phpMonitor.conf.xml &
}

stop() {
	/usr/bin/killall phpMonitor.php	
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 3
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        RETVAL=1
esac


